tasks:
  generateBuildInfo:
    action: !io.github.yuanbaobaoo.petallink.toolchain.generateBuildInfo
      versionPropertiesFile: ${project.rootDir}/gradle.properties
      generatedSourceDir: ${taskOutputDir}

  packageDmg:
    action: !io.github.yuanbaobaoo.petallink.toolchain.runGradle
      unixWrapper: ${project.rootDir}/gradlew
      windowsWrapper: ${project.rootDir}/gradlew.bat
      arguments: [packageDmg, --stacktrace]

  releaseDmg:
    action: !io.github.yuanbaobaoo.petallink.toolchain.runGradle
      unixWrapper: ${project.rootDir}/gradlew
      windowsWrapper: ${project.rootDir}/gradlew.bat
      arguments:
        - jvmTest
        - createReleaseDistributable
        - notarizeReleaseDmg
        - --stacktrace
        - -Prelease=true

generated:
  sources:
    - language: kotlin
      directory: ${tasks.generateBuildInfo.action.generatedSourceDir}

commands:
  - packageDmg
  - releaseDmg
